---

version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:40
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.6
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass

additional_build_steps:
  prepend_base:
    - RUN dnf install -y python3 python3-pip python3-libdnf5
