name: ansible-test images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Monday at 08:00 UTC)
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build:
    name: 'Build ansible-test images (${{ matrix.name }} with Python ${{ matrix.python }})'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: archlinux
            python: '3.11'
          # TODO: re-enable CentOS Stream 8
          # - name: centos-stream8
          #   python: '3.6 3.8 3.9'
          - name: debian-bullseye
            python: '3.9'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install podman buildah
          # Install ansible-core form stable-2.14 until the ansible-core 2.14.2 release is out
          pip install https://github.com/ansible/ansible/archive/stable-2.14.tar.gz
          # pip install ansible-core

      - name: Build ${{ matrix.name }} image
        run: |
          ${{ matrix.name }}/build.sh
        working-directory: ./ansible-test/

      # Right now it is not possible to use some of the images (Debian Bullseye, ArchLinux) with podman in GitHub Actions,
      # while others (CentOS 8 Stream) work fine. This is not specific to the images in this repository, the official
      # ansible-test Ubuntu 20.04 image also does not work with podman in GHA, but does work with Docker in GHA.

      - name: Copy image from podman to docker
        run: |
          podman push localhost/test-image:${{ matrix.name }} docker-daemon:localhost/test-image:${{ matrix.name }}

      - name: Run basic tests with ${{ matrix.name }} image (latest ansible-core release), Python versions ${{ matrix.python }}
        run: |
          for PYTHON in ${{ matrix.python }}; do
            ansible-test integration --color -v --python ${PYTHON} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
          done
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol

      - name: Install ansible-core devel
        run: |
          pip install https://github.com/ansible/ansible/archive/devel.tar.gz

      - name: Run basic tests with ${{ matrix.name }} image (ansible-core devel), Python versions ${{ matrix.python }}
        run: |
          for PYTHON in ${{ matrix.python }}; do
            ansible-test integration --color -v --python ${PYTHON} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
          done
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol
