name: ansible-test images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Monday at 08:00 UTC)
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build:
    name: 'Build ansible-test images (${{ matrix.name }} with Python ${{ matrix.python }})'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: archlinux
            python: '3.11'
          - name: centos-stream8
            python: '3.6 3.9'
          - name: debian-bullseye
            python: '3.9'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install podman buildah
          # Install ansible-core form stable-2.14 until the ansible-core 2.14.2 release is out
          pip install https://github.com/ansible/ansible/archive/stable-2.14.tar.gz
          # pip install ansible-core

      - name: Build ${{ matrix.name }} image
        run: |
          ${{ matrix.name }}/build.sh
        working-directory: ./ansible-test/

      # This is necessary to allow running systemd in rootless containers
      - name: Start systemd user service
        run: |
          loginctl enable-linger runner
          sleep 1

      - name: Run basic tests with ${{ matrix.name }} image (latest ansible-core release), Python versions ${{ matrix.python }}
        run: |
          for PYTHON in ${{ matrix.python }}; do
            ansible-test integration --color -v --python ${PYTHON} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
          done
        env:
          ANSIBLE_TEST_PREFER_PODMAN: 1
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol

      - name: Install ansible-core devel
        run: |
          pip install https://github.com/ansible/ansible/archive/devel.tar.gz

      - name: Run basic tests with ${{ matrix.name }} image (ansible-core devel), Python versions ${{ matrix.python }}
        run: |
          for PYTHON in ${{ matrix.python }}; do
            ansible-test integration --color -v --python ${PYTHON} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
          done
        env:
          ANSIBLE_TEST_PREFER_PODMAN: 1
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol
